usr/bin/xscreensaver
usr/bin/xscreensaver-command
usr/bin/xscreensaver-settings
usr/bin/xscreensaver-demo
usr/libexec/xscreensaver/xscreensaver-auth
usr/libexec/xscreensaver/xscreensaver-gfx
usr/share/applications/xscreensaver-settings.desktop
usr/share/man/man1/xscreensaver.1
usr/share/man/man1/xscreensaver-auth.1
usr/share/man/man1/xscreensaver-gfx.1
usr/share/man/man1/xscreensaver-command.1
usr/share/man/man1/xscreensaver-settings.1
usr/share/man/man1/xscreensaver-demo.1
usr/share/pixmaps/xscreensaver.png
usr/share/fonts/xscreensaver/*
usr/share/xscreensaver/xscreensaver.service usr/lib/systemd/user
debian/xscreensaver.svg /usr/share/pixmaps
usr/share/applications/xscreensaver.desktop usr/share/xscreensaver
debian/xscreensaver-wrapper.sh usr/share/xscreensaver
usr/libexec/xscreensaver/xscreensaver-systemd
usr/share/man/man1/xscreensaver-systemd.1
