#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -L /etc/X11/app-defaults/XScreenSaver ]; then
	    if [ "$(readlink /etc/X11/app-defaults/XScreenSaver)" = "XScreenSaver-nogl" -o \
	         "$(readlink /etc/X11/app-defaults/XScreenSaver)" = "XScreenSaver-gl" ]; then
		rm /etc/X11/app-defaults/XScreenSaver
	    fi
	fi
	;;
esac

# Automatically added by dh_installmenu/13.11.4
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installsystemduser/13.11.4
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'xscreensaver.service' >/dev/null || true
	fi
fi
# End automatically added section

