#!/bin/sh

set -e

# Use the correct app defaults
cd /etc/X11/app-defaults
if [ ! -e XScreenSaver ]; then
    if [ -f XScreenSaver-gl ]; then
	ln -sf XScreenSaver-gl  XScreenSaver
    else
	ln -sf XScreenSaver-nogl XScreenSaver
    fi
fi

# Disable user unit globally, in case it was enabled by 5.44+dfsg1-2
if [ "$1" = "configure" ] && [ "$2" = "5.44+dfsg1-2" -o "$2" = "5.45+dfsg1-1" ]; then
	deb-systemd-helper --user purge xscreensaver.service >/dev/null || true
	deb-systemd-helper --user unmask xscreensaver.service >/dev/null || true
fi

# Automatically added by dh_installsystemduser/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ]; then
		if deb-systemd-helper --user debian-installed 'xscreensaver.service' ; then
			# The following line should be removed in trixie or trixie+1
			deb-systemd-helper --user unmask 'xscreensaver.service' >/dev/null || true

			if deb-systemd-helper --quiet --user was-enabled 'xscreensaver.service' ; then
				# Create new symlinks, if any.
				deb-systemd-helper --user enable 'xscreensaver.service' >/dev/null || true
			fi
		fi

		# Update the statefile to add new symlinks (if any), which need to be cleaned
		# up on purge. Also remove old symlinks.
		deb-systemd-helper --user update-state 'xscreensaver.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu/13.11.4
if [ "$1" = "configure" ] && [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then
	update-menus
fi
# End automatically added section

